# polybot-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: polybot
  labels:
    app: polybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polybot
  template:
    metadata:
        labels:
          app: polybot
    spec:
      containers:
      - name: polybot
        image: selotapetm/polybot-k8s:0.0.3
---
# polybot-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: polybot-svc
spec:
  selector:
    app: polybot
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
