config:
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-svc
        Logstash_Format On
        Retry_Limit False
        Suppress_Type_Name On
        Write_Operation upsert
        Generate_ID On
        Replace_Dots On
  
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-svc
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On
        Write_Operation upsert
        Generate_ID On
        Replace_Dots On