config:
  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name es
        Match kube.*
        Host elasticsearch-svc
        Logstash_Format On
        Retry_Limit False
        Suppress_Type_Name On
        #Write_Operation upsert
        #Generate_ID On
        #Replace_Dots On
        Trace_Error On
  
    [OUTPUT]
        Name es
        Match host.*
        Host elasticsearch-svc
        Logstash_Format On
        Logstash_Prefix node
        Retry_Limit False
        Suppress_Type_Name On
        #Write_Operation upsert
        #Generate_ID On
        #Replace_Dots On
        Trace_Error On
  customParsers: |
    [PARSER]
        Name kube-controller-logs
        Format regex
        Regex'^(?P<timestamp>[^ ]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<log_message>.*)$'
        Time_Key timestamp
        Time_Format "%Y-%m-%dT%H:%M:%S.%L%z"
        Types:
          timestamp: string
          stream: string
          logtag: string
          log_message: string
